// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: delete_ticket_notification_participants.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteTicketNotificaionParticipants = `-- name: DeleteTicketNotificaionParticipants :execresult
DELETE FROM ticket_notification_participants WHERE workspace_id=? AND ref_id=?
`

type DeleteTicketNotificaionParticipantsParams struct {
	WorkspaceID string
	RefID       int64
}

func (q *Queries) DeleteTicketNotificaionParticipants(ctx context.Context, arg DeleteTicketNotificaionParticipantsParams) (sql.Result, error) {
	return q.exec(ctx, q.deleteTicketNotificaionParticipantsStmt, deleteTicketNotificaionParticipants, arg.WorkspaceID, arg.RefID)
}
