// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: delete_tag.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteTag = `-- name: DeleteTag :execresult
DELETE FROM tags WHERE workspace_id=? AND id=?
`

type DeleteTagParams struct {
	WorkspaceID string
	ID          int64
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) (sql.Result, error) {
	return q.exec(ctx, q.deleteTagStmt, deleteTag, arg.WorkspaceID, arg.ID)
}
