// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: delete_tag_workflows.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteAllTagWorkflows = `-- name: DeleteAllTagWorkflows :execresult
DELETE FROM tag_workflows WHERE workspace_id=? AND tag_id=?
`

type DeleteAllTagWorkflowsParams struct {
	WorkspaceID string
	TagID       int64
}

func (q *Queries) DeleteAllTagWorkflows(ctx context.Context, arg DeleteAllTagWorkflowsParams) (sql.Result, error) {
	return q.exec(ctx, q.deleteAllTagWorkflowsStmt, deleteAllTagWorkflows, arg.WorkspaceID, arg.TagID)
}

const deleteTagWorkflows = `-- name: DeleteTagWorkflows :execresult
DELETE FROM tag_workflows WHERE workspace_id=? AND tag_id=? AND workflow_id=?
`

type DeleteTagWorkflowsParams struct {
	WorkspaceID string
	TagID       int64
	WorkflowID  int64
}

func (q *Queries) DeleteTagWorkflows(ctx context.Context, arg DeleteTagWorkflowsParams) (sql.Result, error) {
	return q.exec(ctx, q.deleteTagWorkflowsStmt, deleteTagWorkflows, arg.WorkspaceID, arg.TagID, arg.WorkflowID)
}
