// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: insert_ticket_notification_participants.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTicketNotificationParticipant = `-- name: CreateTicketNotificationParticipant :execresult
INSERT IGNORE INTO ticket_notification_participants (
	workspace_id,
	ref_id,
	participant_id,
	type
)
VALUES (
	?, ?, ?, ?
)
`

type CreateTicketNotificationParticipantParams struct {
	WorkspaceID   string
	RefID         int64
	ParticipantID string
	Type          int8
}

func (q *Queries) CreateTicketNotificationParticipant(ctx context.Context, arg CreateTicketNotificationParticipantParams) (sql.Result, error) {
	return q.exec(ctx, q.createTicketNotificationParticipantStmt, createTicketNotificationParticipant,
		arg.WorkspaceID,
		arg.RefID,
		arg.ParticipantID,
		arg.Type,
	)
}
