// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: insert_tag_workflow_groups.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTagWorkflowGroups = `-- name: CreateTagWorkflowGroups :execresult
INSERT IGNORE INTO tag_workflow_groups (
	workspace_id,
	tag_id,
	workflow_group_id
)
VALUES (
	?, ?, ?
)
`

type CreateTagWorkflowGroupsParams struct {
	WorkspaceID     string
	TagID           int64
	WorkflowGroupID int64
}

func (q *Queries) CreateTagWorkflowGroups(ctx context.Context, arg CreateTagWorkflowGroupsParams) (sql.Result, error) {
	return q.exec(ctx, q.createTagWorkflowGroupsStmt, createTagWorkflowGroups, arg.WorkspaceID, arg.TagID, arg.WorkflowGroupID)
}
