// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: insert_tag_workflows.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTagWorkflows = `-- name: CreateTagWorkflows :execresult
INSERT IGNORE INTO tag_workflows (
	workspace_id,
	tag_id,
	workflow_id
)
VALUES (
	?, ?, ?
)
`

type CreateTagWorkflowsParams struct {
	WorkspaceID string
	TagID       int64
	WorkflowID  int64
}

func (q *Queries) CreateTagWorkflows(ctx context.Context, arg CreateTagWorkflowsParams) (sql.Result, error) {
	return q.exec(ctx, q.createTagWorkflowsStmt, createTagWorkflows, arg.WorkspaceID, arg.TagID, arg.WorkflowID)
}
