// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: insert_tag.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTag = `-- name: CreateTag :execresult
INSERT INTO tags (
	workspace_id,
	id,
	name,
	hash_name,
	description,
	color_src,
	icon_src,
	is_published,
	created_by,
	updated_by,
	version
)
VALUES (
	?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateTagParams struct {
	WorkspaceID string
	ID          int64
	Name        string
	HashName    string
	Description string
	ColorSrc    string
	IconSrc     string
	IsPublished bool
	CreatedBy   int64
	UpdatedBy   int64
	Version     int32
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (sql.Result, error) {
	return q.exec(ctx, q.createTagStmt, createTag,
		arg.WorkspaceID,
		arg.ID,
		arg.Name,
		arg.HashName,
		arg.Description,
		arg.ColorSrc,
		arg.IconSrc,
		arg.IsPublished,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.Version,
	)
}
