// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: insert_ticket.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createTicket = `-- name: CreateTicket :execresult
INSERT INTO tickets (
    workspace_id, workflow_id, id, code, title, priority,
    is_private, status, ref_ticket_ids, workflow, rating_point,
    review, created_by, updated_by, created_at, updated_at
)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type CreateTicketParams struct {
	WorkspaceID  string
	WorkflowID   int64
	ID           int64
	Code         string
	Title        string
	Priority     int8
	IsPrivate    bool
	Status       int8
	RefTicketIds json.RawMessage
	Workflow     json.RawMessage
	RatingPoint  int8
	Review       string
	CreatedBy    int64
	UpdatedBy    int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (sql.Result, error) {
	return q.exec(ctx, q.createTicketStmt, createTicket,
		arg.WorkspaceID,
		arg.WorkflowID,
		arg.ID,
		arg.Code,
		arg.Title,
		arg.Priority,
		arg.IsPrivate,
		arg.Status,
		arg.RefTicketIds,
		arg.Workflow,
		arg.RatingPoint,
		arg.Review,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}
