// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AdditionalRequest struct {
	WorkspaceID         string
	TicketID            int64
	NodeID              int64
	ID                  int64
	RequesterID         int64
	TargetID            int64
	ContentNeedAdd      string
	ResponseToRequester string
	AttachedFiles       json.RawMessage
	Status              int8
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type AdvanceSetting struct {
	CreatedBy                           int64
	UpdatedBy                           int64
	CreatedAt                           sql.NullTime
	UpdatedAt                           sql.NullTime
	WorkspaceID                         string
	WorkflowID                          int64
	IsPublished                         bool
	Version                             int32
	AdminOptionParticipantValue         int32
	AdminOptionParticipantRef           int64
	AllowCancelValue                    int32
	AllowCancelParticipantValue         int32
	AllowCancelParticipantRef           int64
	AllowDeleteValue                    int32
	AllowDeleteParticipantValue         int32
	AllowDeleteParticipantRef           int64
	CloseOptionValue                    int32
	CloseOptionParticipantValue         int32
	CloseOptionParticipantRef           int64
	RateOptionValue                     int32
	ApproveBeforeOnHoldValue            int32
	ApproveBeforeOnHoldParticipantValue int32
	ApproveBeforeOnHoldParticipantRef   int64
}

type AdvanceSettingParticipant struct {
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	WorkspaceID   string
	RefID         int64
	ParticipantID string
	Type          int8
}

type Currency struct {
	WorkspaceID string
	ID          int64
	Name        string
	Code        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type DateOff struct {
	WorkspaceID string
	ShiftID     int64
	ID          int64
	Name        string
	StartDate   sql.NullTime
	EndDate     sql.NullTime
	IsAnnual    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Edge struct {
	WorkspaceID   string
	WorkflowID    int64
	CurrentNodeID int64
	NextNodeID    int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type MyTicket struct {
	WorkspaceID                string
	WorkflowID                 int64
	ID                         int64
	Code                       string
	Title                      string
	Priority                   int8
	IsPrivate                  bool
	Status                     int8
	CurrentNodeID              int64
	CurrentNodeName            string
	CurrentNodeStatus          int8
	CurrentNodeType            int8
	NodeDeadlineAt             sql.NullTime
	AssigneeID                 sql.NullInt64
	DepartmentID               sql.NullString
	Workflow                   json.RawMessage
	Tags                       json.RawMessage
	RefTicketIds               json.RawMessage
	RatingPoint                int8
	Review                     string
	LatestRecentActivityUserID sql.NullInt64
	LatestRecentActivityAt     sql.NullTime
	CreatedBy                  int64
	UpdatedBy                  int64
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

type Node struct {
	WorkspaceID      string
	WorkflowID       int64
	ID               int64
	Type             int8
	CompressedOption json.RawMessage
	SlaID            int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type NodeParticipant struct {
	WorkspaceID     string
	NodeID          int64
	ParticipantID   string
	RoleType        int8
	ParticipantType int8
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type OnHoldRequest struct {
	WorkspaceID   string
	TicketID      int64
	NodeID        int64
	ID            int64
	RequesterID   int64
	Reason        sql.NullString
	ImageUrls     json.RawMessage
	AttachedFiles json.RawMessage
	Status        int8
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type OnHoldRequestApprover struct {
	WorkspaceID     string
	TicketID        int64
	OnHoldRequestID int64
	ApproverID      int64
}

type Participant struct {
	WorkspaceID string
	ID          string
	Name        string
	Type        int8
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ParticipantMember struct {
	WorkspaceID   string
	ParticipantID string
	UserID        int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Prefix struct {
	WorkspaceID string
	ID          int64
	Name        string
	Description string
	IsDefault   bool
	Status      int8
	UpdatedBy   int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Shift struct {
	WorkspaceID string
	ID          int64
	Title       string
	Description string
	IsDefault   bool
	TimezoneIdx int8
	Status      int8
	WorkingType int8
	UpdatedBy   int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Sla struct {
	WorkspaceID       string
	ID                int64
	Name              string
	ShiftID           int64
	IsDefault         bool
	Status            int8
	SlaPriorityLevels json.RawMessage
	SlaNotifications  json.RawMessage
	Version           int32
	IsDeleted         bool
	CreatedBy         int64
	UpdatedBy         int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Tag struct {
	WorkspaceID string
	ID          int64
	Name        string
	HashName    string
	ColorSrc    string
	IconSrc     string
	Description string
	IsPublished bool
	Version     int32
	IsDeleted   bool
	CreatedBy   int64
	UpdatedBy   int64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type TagWorkflow struct {
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	WorkspaceID string
	TagID       int64
	WorkflowID  int64
}

type TagWorkflowGroup struct {
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	WorkspaceID     string
	TagID           int64
	WorkflowGroupID int64
}

type Task struct {
	WorkspaceID             string
	NodeID                  int64
	ID                      int64
	Name                    string
	Description             string
	EstimateDurationMinutes int32
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

type TaskParticipant struct {
	WorkspaceID     string
	TaskID          int64
	ParticipantID   string
	RoleType        int8
	ParticipantType int8
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Ticket struct {
	WorkspaceID  string
	WorkflowID   int64
	ID           int64
	Code         string
	Title        string
	Priority     int8
	IsPrivate    bool
	Status       int8
	Workflow     json.RawMessage
	RefTicketIds json.RawMessage
	RatingPoint  int8
	Review       string
	CreatedBy    int64
	UpdatedBy    int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type TicketActivity struct {
	WorkspaceID string
	TicketID    int64
	ID          int64
	ActorID     string
	ActorType   int8
	Type        int8
	TargetID    string
	TargetType  int8
	ObjectID    string
	ObjectType  int8
	Content     json.RawMessage
	CreatedAt   time.Time
}

type TicketAdvanceSettingParticipant struct {
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	WorkspaceID   string
	RefID         int64
	ParticipantID string
	TicketID      int64
	Type          int8
	ActionType    int8
}

type TicketEdge struct {
	WorkspaceID   string
	TicketID      int64
	CurrentNodeID int64
	NextNodeID    int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type TicketField struct {
	WorkspaceID string
	TicketID    int64
	FieldID     int64
	Info        json.RawMessage
	Value       json.RawMessage
}

type TicketFlowchartHistory struct {
	WorkspaceID string
	TicketID    int64
	ID          int64
	Flowchart   json.RawMessage
	CreatedAt   time.Time
}

type TicketNode struct {
	WorkspaceID     string
	TicketID        int64
	NodeID          int64
	AssigneeID      int64
	Status          int8
	Type            int8
	Sla             json.RawMessage
	Option          json.RawMessage
	Deadline        sql.NullTime
	FirstResponseAt sql.NullTime
	StartedAt       sql.NullTime
	UpdatedBy       sql.NullInt64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type TicketNodeParticipant struct {
	WorkspaceID     string
	TicketID        int64
	NodeID          int64
	ParticipantID   string
	RoleType        int8
	ParticipantType int8
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type TicketNotification struct {
	CreatedBy                                  int64
	UpdatedBy                                  int64
	CreatedAt                                  sql.NullTime
	UpdatedAt                                  sql.NullTime
	WorkspaceID                                string
	ID                                         int64
	IsPublished                                bool
	Version                                    int32
	CreatedRequestValue                        int32
	CreatedRequestParticipantValue             int32
	CreatedRequestParticipantRef               int64
	UpdatedAsigneeValue                        int32
	UpdatedAsigneeParticipantValue             int32
	UpdatedAsigneeParticipantRef               int64
	UpdatedTicketValue                         int32
	UpdatedTicketParticipantValue              int32
	UpdatedTicketParticipantRef                int64
	UpdatedWorkflowValue                       int32
	UpdatedWorkflowParticipantValue            int32
	UpdatedWorkflowParticipantRef              int64
	UpdatedStatusStepValue                     int32
	UpdatedStatusStepParticipantValue          int32
	UpdatedStatusStepParticipantRef            int64
	UpdatedCommentValue                        int32
	UpdatedCommentParticipantValue             int32
	UpdatedCommentParticipantRef               int64
	UpdatedFollowerOrSupporterValue            int32
	UpdatedFollowerOrSupporterParticipantValue int32
	UpdatedFollowerOrSupporterParticipantRef   int64
	UpdatedRatingServiceValue                  int32
	UpdatedRatingServiceParticipantValue       int32
	UpdatedRatingServiceParticipantRef         int64
	AlmostExpiredFirstResponseValue            int32
	AlmostExpiredFirstResponseParticipantValue int32
	AlmostExpiredFirstResponseParticipantRef   int64
	AlmostExpiredProcessTicketValue            int32
	AlmostExpiredProcessTicketParticipantValue int32
	AlmostExpiredProcessTicketParticipantRef   int64
	ExpiredFirstResponseValue                  int32
	ExpiredFirstResponseParticipantValue       int32
	ExpiredFirstResponseParticipantRef         int64
	ExpiredProcessTicketValue                  int32
	ExpiredProcessTicketParticipantValue       int32
	ExpiredProcessTicketParticipantRef         int64
}

type TicketNotificationParticipant struct {
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	WorkspaceID   string
	RefID         int64
	ParticipantID string
	Type          int8
}

type TicketTag struct {
	TicketID  int64
	TagID     int64
	Tag       json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Unfollow struct {
	WorkspaceID string
	UserID      int64
	TicketID    int64
}

type WeeklySetting struct {
	WorkspaceID     string
	ShiftID         int64
	ID              int64
	DayOfWeek       int8
	Start           int16
	End             int16
	IsActive        bool
	HasBreakTime    bool
	IsWorkingAllDay bool
	StartBreak      sql.NullInt16
	EndBreak        sql.NullInt16
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Workflow struct {
	WorkspaceID     string
	WorkflowGroupID int64
	ID              int64
	Name            string
	ColorSrc        string
	IconSrc         string
	Description     string
	PrefixID        int64
	State           int8
	CreatedBy       int64
	UpdatedBy       int64
	IsPublished     bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type WorkflowFormField struct {
	WorkspaceID      string
	WorkflowID       int64
	ID               int64
	ParentID         int64
	Title            string
	Hint             string
	Type             int8
	IsRequired       bool
	Version          int16
	CompressedOption json.RawMessage
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type WorkflowGroup struct {
	WorkspaceID   string
	ID            int64
	ParentID      int64
	Name          string
	LeftBower     int16
	RightBower    int16
	WorkflowCount int16
	HLevel        int16
	Version       int16
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
