// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: review_ticket.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const reviewTicket = `-- name: ReviewTicket :execresult
UPDATE tickets SET
    rating_point = ?,
    review = ?,
    updated_by = ?,
    updated_at = ?
WHERE workspace_id = ?
  AND id = ?
`

type ReviewTicketParams struct {
	RatingPoint int8
	Review      string
	UpdatedBy   int64
	UpdatedAt   time.Time
	WorkspaceID string
	ID          int64
}

func (q *Queries) ReviewTicket(ctx context.Context, arg ReviewTicketParams) (sql.Result, error) {
	return q.exec(ctx, q.reviewTicketStmt, reviewTicket,
		arg.RatingPoint,
		arg.Review,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.ID,
	)
}
