// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: update_tag.sql

package sqlc

import (
	"context"
	"database/sql"
)

const updateTag = `-- name: UpdateTag :execresult
UPDATE tags SET
	name=?,
	hash_name=?,
	description=?,
	color_src=?,
	icon_src=?,
	is_published=?,
	updated_by=?,
	updated_at=?
WHERE workspace_id=? AND id=?
`

type UpdateTagParams struct {
	Name        string
	HashName    string
	Description string
	ColorSrc    string
	IconSrc     string
	IsPublished bool
	UpdatedBy   int64
	UpdatedAt   sql.NullTime
	WorkspaceID string
	ID          int64
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (sql.Result, error) {
	return q.exec(ctx, q.updateTagStmt, updateTag,
		arg.Name,
		arg.HashName,
		arg.Description,
		arg.ColorSrc,
		arg.IconSrc,
		arg.IsPublished,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.ID,
	)
}
