// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: update_ticket_status.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const updateTicketStatus = `-- name: UpdateTicketStatus :execresult
UPDATE tickets SET
    status = ?,
    updated_at = ?
WHERE workspace_id = ?
  AND id = ?
`

type UpdateTicketStatusParams struct {
	Status      int8
	UpdatedAt   time.Time
	WorkspaceID string
	ID          int64
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (sql.Result, error) {
	return q.exec(ctx, q.updateTicketStatusStmt, updateTicketStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.ID,
	)
}
