// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: update_ticket_node_assignee.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const updateTicketNodeAssignee = `-- name: UpdateTicketNodeAssignee :execresult
UPDATE ticket_nodes
SET
    assignee_id=?,
    deadline=?,
    status=?,
    updated_at=?
WHERE workspace_id=? AND ticket_id=? AND node_id=?
`

type UpdateTicketNodeAssigneeParams struct {
	AssigneeID  int64
	Deadline    sql.NullTime
	Status      int8
	UpdatedAt   time.Time
	WorkspaceID string
	TicketID    int64
	NodeID      int64
}

func (q *Queries) UpdateTicketNodeAssignee(ctx context.Context, arg UpdateTicketNodeAssigneeParams) (sql.Result, error) {
	return q.exec(ctx, q.updateTicketNodeAssigneeStmt, updateTicketNodeAssignee,
		arg.AssigneeID,
		arg.Deadline,
		arg.Status,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.TicketID,
		arg.NodeID,
	)
}
