// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: write_sla.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createSla = `-- name: CreateSla :execresult
INSERT INTO slas (
    workspace_id, id, name, shift_id, is_default, status,
    sla_priority_levels, sla_notifications,
    version, is_deleted, created_by, updated_by, created_at, updated_at
)
VALUES (
        ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateSlaParams struct {
	WorkspaceID       string
	ID                int64
	Name              string
	ShiftID           int64
	IsDefault         bool
	Status            int8
	SlaPriorityLevels json.RawMessage
	SlaNotifications  json.RawMessage
	Version           int32
	IsDeleted         bool
	CreatedBy         int64
	UpdatedBy         int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) CreateSla(ctx context.Context, arg CreateSlaParams) (sql.Result, error) {
	return q.exec(ctx, q.createSlaStmt, createSla,
		arg.WorkspaceID,
		arg.ID,
		arg.Name,
		arg.ShiftID,
		arg.IsDefault,
		arg.Status,
		arg.SlaPriorityLevels,
		arg.SlaNotifications,
		arg.Version,
		arg.IsDeleted,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}
