// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: write_ticket_edge.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createTicketEdge = `-- name: CreateTicketEdge :execresult
insert into ticket_edges (workspace_id, ticket_id, current_node_id, next_node_id, created_at,
                          updated_at)
values (?, ?, ?, ?, ?, ?)
`

type CreateTicketEdgeParams struct {
	WorkspaceID   string
	TicketID      int64
	CurrentNodeID int64
	NextNodeID    int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateTicketEdge(ctx context.Context, arg CreateTicketEdgeParams) (sql.Result, error) {
	return q.exec(ctx, q.createTicketEdgeStmt, createTicketEdge,
		arg.WorkspaceID,
		arg.TicketID,
		arg.CurrentNodeID,
		arg.NextNodeID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}
