// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: write_ticket_flowchart_history.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createTicketFlowchartHistory = `-- name: CreateTicketFlowchartHistory :execresult
insert into ticket_flowchart_histories (workspace_id, ticket_id, id, flowchart,
                                        created_at)
values (?, ?, ?, ?, ?)
`

type CreateTicketFlowchartHistoryParams struct {
	WorkspaceID string
	TicketID    int64
	ID          int64
	Flowchart   json.RawMessage
	CreatedAt   time.Time
}

func (q *Queries) CreateTicketFlowchartHistory(ctx context.Context, arg CreateTicketFlowchartHistoryParams) (sql.Result, error) {
	return q.exec(ctx, q.createTicketFlowchartHistoryStmt, createTicketFlowchartHistory,
		arg.WorkspaceID,
		arg.TicketID,
		arg.ID,
		arg.Flowchart,
		arg.CreatedAt,
	)
}
