// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: write_unfollow.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUnfollow = `-- name: CreateUnfollow :execresult
insert ignore into unfollows (
    workspace_id,
    ticket_id,
    user_id
) values (
    ?,
    ?,
    ?
)
`

type CreateUnfollowParams struct {
	WorkspaceID string
	TicketID    int64
	UserID      int64
}

func (q *Queries) CreateUnfollow(ctx context.Context, arg CreateUnfollowParams) (sql.Result, error) {
	return q.exec(ctx, q.createUnfollowStmt, createUnfollow, arg.WorkspaceID, arg.TicketID, arg.UserID)
}

const deleteUnfollow = `-- name: DeleteUnfollow :execresult
delete from unfollows
where workspace_id = ?
  and ticket_id = ?
  and user_id = ?
`

type DeleteUnfollowParams struct {
	WorkspaceID string
	TicketID    int64
	UserID      int64
}

func (q *Queries) DeleteUnfollow(ctx context.Context, arg DeleteUnfollowParams) (sql.Result, error) {
	return q.exec(ctx, q.deleteUnfollowStmt, deleteUnfollow, arg.WorkspaceID, arg.TicketID, arg.UserID)
}
