// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: write_task.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createTask = `-- name: CreateTask :execresult
INSERT INTO tasks
(workspace_id, node_id, id, name, description, estimate_duration_minutes, created_at, updated_at)
VALUES(?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	WorkspaceID             string
	NodeID                  int64
	ID                      int64
	Name                    string
	Description             string
	EstimateDurationMinutes int32
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (sql.Result, error) {
	return q.exec(ctx, q.createTaskStmt, createTask,
		arg.WorkspaceID,
		arg.NodeID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.EstimateDurationMinutes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteTask = `-- name: DeleteTask :execresult
DELETE FROM tasks
WHERE workspace_id = ?
  AND node_id = ?
  AND id = ?
`

type DeleteTaskParams struct {
	WorkspaceID string
	NodeID      int64
	ID          int64
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (sql.Result, error) {
	return q.exec(ctx, q.deleteTaskStmt, deleteTask, arg.WorkspaceID, arg.NodeID, arg.ID)
}
