// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: write_on_hold_request_approver.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createOnHoldRequestApprover = `-- name: CreateOnHoldRequestApprover :execresult
insert into on_hold_request_approvers (workspace_id, ticket_id,
                                       on_hold_request_id, approver_id)
values (?, ?, ?, ?)
`

type CreateOnHoldRequestApproverParams struct {
	WorkspaceID     string
	TicketID        int64
	OnHoldRequestID int64
	ApproverID      int64
}

func (q *Queries) CreateOnHoldRequestApprover(ctx context.Context, arg CreateOnHoldRequestApproverParams) (sql.Result, error) {
	return q.exec(ctx, q.createOnHoldRequestApproverStmt, createOnHoldRequestApprover,
		arg.WorkspaceID,
		arg.TicketID,
		arg.OnHoldRequestID,
		arg.ApproverID,
	)
}
