// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: write_ticket_advance_setting_participant.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTicketAdvanceSettingParticipant = `-- name: CreateTicketAdvanceSettingParticipant :execresult
INSERT IGNORE INTO ticket_advance_setting_participants(
    created_at, updated_at, workspace_id, ref_id, participant_id,
    ticket_id, type, action_type
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTicketAdvanceSettingParticipantParams struct {
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	WorkspaceID   string
	RefID         int64
	ParticipantID string
	TicketID      int64
	Type          int8
	ActionType    int8
}

func (q *Queries) CreateTicketAdvanceSettingParticipant(ctx context.Context, arg CreateTicketAdvanceSettingParticipantParams) (sql.Result, error) {
	return q.exec(ctx, q.createTicketAdvanceSettingParticipantStmt, createTicketAdvanceSettingParticipant,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.RefID,
		arg.ParticipantID,
		arg.TicketID,
		arg.Type,
		arg.ActionType,
	)
}
