// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: write_ticket_tag.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createTicketTag = `-- name: CreateTicketTag :execresult
insert into ticket_tags (ticket_id, tag_id, tag, created_at, updated_at)
values (?,?, ?, ?, ?)
`

type CreateTicketTagParams struct {
	TicketID  int64
	TagID     int64
	Tag       json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateTicketTag(ctx context.Context, arg CreateTicketTagParams) (sql.Result, error) {
	return q.exec(ctx, q.createTicketTagStmt, createTicketTag,
		arg.TicketID,
		arg.TagID,
		arg.Tag,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}
